name: release
on:
  # Only trigger on version tags
  push:
    tags:
      - 'v*'
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: write             # allow tag + release
  pull-requests: write        # allow the bot to open/refresh PRs
  actions: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}